### PR TITLE
Optional academic disciplines

### PR DESCRIPTION
**Pull request by rerb**
Makes Academic Disciplines an optional field for all content types except Academic Programs, Research Centers & Institutes, and Course Materials, where they're required by the SubmitResourceForm.

Closes https://github.com/AASHE/hub/issues/85.

### CODE REVIEW

**Comment by bartTC** [comment]
@rerb if 'Academic programs' won't be the only field that is set required per content-type, I'd lean to do it the way we handle the `label_overrides` already here: 5ef8449a58e3e3a7c66c948f182f8c37759e790b

You could return a list of (ContentType) fields which are required for certain SubClasses.

**Comment by bartTC** [comment]
I'd also either move [this code](https://github.com/AASHE/hub/blob/5ef8449a58e3e3a7c66c948f182f8c37759e790b/hub/apps/submit/views.py#L97-L105) to the `DocumentForm.__init__` method or above academic override code to the view, so those per-content-type-subclass adjustments are at the same place.

**Comment by jamstooks** [comment]
I think that makes sense. I like @rerb's approach and you suggestion seems like a logical next step for versatility. I could see a method called `required_field_overrides` that returns a dict of fields, like:

    @classmethod
    def required_field_overrides(cls):
       return {'disciplines': True}

Either way presents the possible issue of overriding a field that is required at the database level... so we'll need to keep an eye on that.

**Comment by jamstooks** [comment]
Whoops. Sorry, didn't mean to close.

**Comment by bartTC** [comment]
:+1:

**Pull request merged**
